name: Create Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: idmc92/exam:latest

      - name: EC2 Application Deploy
        run: |
          ssh -i ${{ secrets.SSH_KEY_PATH }} ubuntu@3.147.44.185 "docker stop simple-chat-container" 
          ssh -i ${{ secrets.SSH_KEY_PATH }} ubuntu@3.147.44.185 "docker pull idmc92/exam:latest"
          ssh -i ${{ secrets.SSH_KEY_PATH }} ubuntu@3.147.44.185 "docker run -d -p 80:3000 --name simple-chat-container idmc92/exam:latest"
        env:
          SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}    